### ISSUE TITLE
Date format in file browser has invalid format

### ISSUE THREAD

**Issue by baconlive** [opicron/mysticbbs-vbase#1]
Hello,
using your script when i'm browsing files the upload date is wrong, it should be something related to parsing or format.

For example a file uploaded on 26/03/2024 shows as uploaded on Dec 03 2030.

Can you fix it?

Thanks,
Guido

**Comment by opicron** [comment]
I fixed this issue now that I updated to Mystic A49. vBase is now compatible with both A47 and A49 versions.
