### ISSUE TITLE
pyfiglet error: requested font (opts.fonttr} not found

### ISSUE THREAD

**Issue by voipmeister** [opicron/mysticbbs-vbase#2]
Trying to configure vbase for my board, downloaded version 0.1 beta from your board.
I ran into an issue regarding pyfiglet fonts and wonder if I am missing a font?

```
PYTHON ERROR (/mystic/themes/global/scripts/ubase.mpy)
  File "mystic/themes/global/scripts/ubase.mpy", line 89, in ‹module >
    from pyfiglet import Figlet
  File "/usr/lib/python2.?/site-packages/pyfiglet/_init_-py", line 1004
    print(f"pyfiglet error: requested font (opts.fonttr} not found.")
SyntaxError: invalid syntax
Press a key
```

Some more info:
* Mystic version 1.12A48
* Rocky Linux 8
* Python 2.7

Any insight greatly appreciated!

**Comment by voipmeister** [comment]
For good measure I also tried the github version, with the same result :)

**Comment by opicron** [comment]
Ah, this is because the figlet module could not be loaded. It has to be installed in python. However, of course I should make it optional. I will add a exception to avoid this.

To add the figlet module, I think the command is `pip install pyfiglet`.

**Comment by voipmeister** [comment]
Hi oP,

It is installed:
```
bash-4.4$ pip2 freeze
pyfiglet==1.0.0
bash-4.4$
```

However, if it's not mandatory an exception would be nice :)

**Comment by opicron** [comment]
Fixed!
